version: 39
jobs:
- name: validate-flake
  steps:
  - !CheckoutStep
    name: checkout repo
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetupCacheStep
    name: nix-cache
    key: nix-cache
    paths:
    - /nix/store
    uploadStrategy: UPLOAD_IF_NOT_HIT
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: use nix shell to check the flake
    runInContainer: true
    image: nixos/nix:latest
    interpreter: /root/.nix-profile/bin/bash
      commands: |
        nix-shell -p git && nix flake check
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
