version: 1

jobs:
  - name: validate-flake
    image: nixos/nix:latest

    caches:
      - key: nix-store
        path: /nix/store

    steps:
      - name: Install git (required by flakes)
        commands:
          - apt-get update && apt-get install -y git

      - name: Validate flake.nix
        commands:
          - nix flake check
